CREATE DATABASE IF NOT EXISTS betting_manager;
USE betting_manager;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  sport VARCHAR(80) NOT NULL,
  sportsbook VARCHAR(120) NULL,
  bet_type VARCHAR(80) NOT NULL,
  leg_count INT NULL,
  market VARCHAR(255) NOT NULL,
  odds INT NOT NULL,
  stake DECIMAL(10, 2) NOT NULL,
  result ENUM('win', 'loss', 'push') NOT NULL,
  profit_loss DECIMAL(10, 2) NOT NULL DEFAULT 0,
  bet_date DATE NOT NULL,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_bets_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bankroll_profiles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL UNIQUE,
  starting_bankroll DECIMAL(10, 2) NOT NULL DEFAULT 0,
  unit_size DECIMAL(10, 2) NOT NULL DEFAULT 10,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_bankroll_profiles_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS saved_bet_options (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  option_type ENUM('sport', 'sportsbook', 'bet_type') NOT NULL,
  option_value VARCHAR(120) NOT NULL,
  last_used_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_saved_bet_options_user_type_value (user_id, option_type, option_value),
  CONSTRAINT fk_saved_bet_options_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bet_legs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bet_id INT NOT NULL,
  sport VARCHAR(80) NULL,
  market VARCHAR(255) NOT NULL,
  leg_order INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_bet_legs_bets FOREIGN KEY (bet_id) REFERENCES bets(id) ON DELETE CASCADE
);
